### PR TITLE
CDI-673 Revisit manipulation with InjectionPoint(s) in ProducerConfigurator Remove methods related to injectionPoints

### PR DESCRIPTION
**Pull request by antoinesd**
CDI-673 Revisit manipulation with InjectionPoint(s) in ProducerConfigurator
Remove methods related to injectionPoints

### CODE REVIEW

**Comment by tremes** [comment]
Spec text in `11.5.11.1. ProducerConfigurator interface` needs some update as wll. Otherwise looks good.

**Comment by antoinesd** [comment]
Corrected. Thanks Tomas

**Comment by mkouba** [comment]
Looks good now.

**Comment by manovotn** [comment]
+1 from me

**Pull request merged**
