### PR TITLE
CDI-485 Literals for built-in annotations

### PR DESCRIPTION
**Pull request by mkouba**
https://issues.jboss.org/browse/CDI-485

### CODE REVIEW

**Comment by antoinesd** [comment]
Looks good for me

**Comment by sknitelius** [comment]
Looks good.

**Comment by mkouba** [comment]
Two things I'm not so sure about are:
1. The name of the default instance, e.g. `Any.Literal.DEFAULT` is ok, `Default.Literal.DEFAULT` is not so nice. On the other hand `DEFAULT_INSTANCE` is too long. Maybe `INSTANCE`...
2. Whether we should allow to instantiate literals which currently only supply default instances (`Default`, `Any`, etc.). Currently, it's not allowed.

**Comment by antoinesd** [comment]
> 1. The name of the default instance, e.g. Any.Literal.DEFAULT is ok, Default.Literal.DEFAULT is not so nice. On the other hand DEFAULT_INSTANCE is too long. Maybe INSTANCE...

I prefer INSTANCE. It is the name used in DeltaSpike and late Seam solder.

> 2. Whether we should allow to instantiate literals which currently only supply default instances (Default, Any, etc.). Currently, it's not allowed.

The only interest would be for the sake of consistency with Literals having fields... But I think it's ok like that.

**Comment by mkouba** [comment]
* renamed default instance to `INSTANCE`
* removed most private constructors - it's nothing against nothing

**Pull request merged**
