### PR TITLE
CDI-642 Allow defining interceptor binding or qualifier with an AnnotatedTypeConfigurator

### PR DESCRIPTION
**Pull request by antoinesd**
CDI-642 Allow defining interceptor binding or qualifier with an AnnotatedTypeConfigurator

### CODE REVIEW

**Comment by antoinesd** [comment]
Spec part not written yet: API should be discussed first.

**Comment by mkouba** [comment]
Hm, shouldn't the methods accept `Class<T>` arguments? Similarly as `javax.enterprise.inject.spi.BeforeBeanDiscovery.addAnnotatedType(Class<T>, String)`?

I also don't like the names. Maybe we could name the methods `configureQualifier(Class)` and `configureInterceptorBinding(Class)` since we're basically configuring the original definitions?

**Comment by antoinesd** [comment]
Agree on both points. changing the PR in that direction

**Comment by mkouba** [comment]
Looks good. We should merge it ASAP so that we can identify possible implementation problems in time ;-)

**Pull request merged**
