### PR TITLE
CDI-571 producer and disposer methods can be only local bussines meth…

### PR DESCRIPTION
**Pull request by tremes**
…od of EJB.

### CODE REVIEW

**Comment by mkouba** [comment]
I'm not sure `local business method` is the best name. I've searched the EJB spec and it's only used twice (9.4.2.3) and apparently in a different sense. I think we should follow the terminology from "3.2 Local, Remote, and Web Service Client Views", although it's a bit verbose. E.g. something like `business method exposed by a local business interface or by a no-interface view`...

**Comment by tremes** [comment]
Yes that's true and sounds reasonable. I changed the all related wording.

**Comment by antoinesd** [comment]
+1 for me

**Comment by johnament** [comment]
+1 from me

**Pull request merged**
