### PR TITLE
CDI-637 rename the builder package to configurator and fix some langu…

### PR DESCRIPTION
**Pull request by tremes**
…age.

### CODE REVIEW

**Comment by johnament** [comment]
LGTM

**Comment by antoinesd** [comment]
There still reference to `javax.enterprise.inject.spi.builder` package in the spec document in SPI chapter.

**Comment by tremes** [comment]
Yes good catch! Already updated.

**Comment by antoinesd** [comment]
You're so fast @tremes !. Looks good now

**Comment by mkouba** [comment]
Looks good.

**Pull request merged**
