### PR TITLE
CDI-633 Deprecate fireEvent() method more explictly in spec doc

### PR DESCRIPTION
**Pull request by antoinesd**
Deprecate fireEvent() method more explictly in spec doc

### CODE REVIEW

**Comment by mkouba** [comment]
-1

We should not remove entire sections - it's not consistent with what we did in CDI 1.1 and 1.2, see for example "@New qualified beans".

**Comment by tremes** [comment]
Uf we should not likely remove all the text describing the original behaviour. I agree. But it seemed to me that this section `fireEvent() method` was introduced accidentally by the previous commit.

**Comment by manovotn** [comment]
@tremes I think the only added text was about deprication of the `fireEvent` method.
Anyway I agree with Martin. We might not want to keep the whole text though. Can we just keep the first few lines up to (and excluding) the source code part? The detailed description of method args could be left out since we deprecate it.

**Comment by antoinesd** [comment]
@mkouba it IS consistent with what we did in CDI 1.1 look at the end of sections: http://docs.jboss.org/cdi/spec/1.2/cdi-spec.html#bm_obtain_injectiontarget

IMO the `@New` section was let in place because nothing replaced it

**Comment by mkouba** [comment]
Ok, fine. All the information is in javadoc anyway. +0 from me then ;-)

**Comment by Emily-Jiang** [comment]
The javadoc should not be deleted as it is just deprecated not being deleted.

**Comment by johnament** [comment]
@Emily-Jiang  the javadoc was not deleted.

**Comment by Emily-Jiang** [comment]
I meant the whole section should not be deleted from the spec :o.

**Comment by antoinesd** [comment]
@Emily-Jiang it was not deleted but replaced by one sentence like we did for `createInjectionTarget()` during CDI 1.1 : http://docs.jboss.org/cdi/spec/1.2/cdi-spec.html#bm_obtain_injectiontarget

Chapter 11 is already 35 pages long (nearly 20% of the spec), removing section for deprecated feature is one solution to avoid bloating the doc.

For the record, in Java EE, when a feature is deprecated it's not removed from the spec but its usage is not encouraged...

**Comment by johnament** [comment]
+1 to this change  - if we're deprecating it, we shouldn't provide info to new users.

**Pull request merged**
