### PR TITLE
CDI-602 Set UnmanagedInstance.disposed to true during dispose()

### PR DESCRIPTION
**Pull request by mkouba**

### CODE REVIEW

**Comment by antoinesd** [comment]
+1 for me

**Comment by tremes** [comment]
I think this `IllegalStateException` could be mentioned also in spec text. WDYT?

**Comment by mkouba** [comment]
@tremes Assertions may be implied, right?

**Comment by antoinesd** [comment]
@tremes what Martin did was to make working a use case described in javadoc.
The problem with `Unmanaged` is that the spec doesn't describe the class, just show an example in 11.3.4.

**Pull request merged**
